# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    desc: "Builds the firecracker-land binary"
    cmds:
      - echo "Building firecracker-land binary..."
      - go build --tags netgo --ldflags '-s -w -extldflags "-lm -lstdc++ -static"' -o bin *.go
      - echo "Done!"
  run:
    desc: "Runs the firecracker-land binary"
    cmds:
      - echo "Running firecracker-land binary..."
      - ./bin
  clean:
    desc: "Cleans up the firecracker-land binary"
    cmds:
      - echo "Cleaning up..."
      - rm -rf bin
      - rm -rf vmlinux.bin
      - echo "Done!"
  pull-kernel:
    desc: "Pulls the kernel from the S3 bucket"
    cmds:
      - echo "Pulling the kernel..."
      - arch=$(uname -m)
      - if [ ! -f "$PWD/vmlinux.bin" ]; 
          then 
            echo "Kernel does not exist! Downloading...";
            wget "https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/$(arch)/kernels/vmlinux.bin";
        else
          echo "Kernel already exists!";
        fi
      - echo "Done!"
  extract-init-base-tar:
    desc: "Extract init base tar..."
    cmds:
      - echo "Extract for extracting rootfs process from docker image..."
      - docker build -t drop/custom-init .
      - echo "Done Building!"
      - echo "Starting extraction process..."
      - docker rm -f custom-init
      - rm -rf rootfs.tar
      - docker create --name custom-init drop/custom-init
      - docker export custom-init -o rootfs.tar
      - docker rm -f custom-init
      - echo "Done Extraction!"



    
  
