# https://taskfile.dev

version: '3'

silent: true

tasks:
  build:
    desc: "Builds the firecracker-land binary"
    cmds:
      - echo "Building firecracker-land binary..."
      - go build --tags netgo --ldflags '-s -w -extldflags "-lm -lstdc++ -static"' -o bin *.go
      - echo "Done!"
  run:
    desc: "Runs the firecracker-land binary"
    cmds:
      - echo "Running firecracker-land binary..."
      - ./bin
  clean:
    desc: "Cleans up the firecracker-land binary"
    cmds:
      - echo "Cleaning up..."
      - rm -rf bin
      - rm -rf vmlinux.bin
      - rm -rf init
      - rm -rf initrd.cpio
      - rm -rf *.img
      - rm -rf *.ext4
      - echo "Done!"
  pull-kernel:
    desc: "Pulls the kernel from the S3 bucket"
    cmds:
      - echo "Pulling the kernel..."
      - arch=$(uname -m)
      - if [ ! -f "$PWD/vmlinux.bin" ]; 
          then 
            echo "Kernel does not exist! Downloading...";
            wget "https://s3.amazonaws.com/spec.ccfc.min/img/quickstart_guide/$(arch)/kernels/vmlinux.bin";
        else
          echo "Kernel already exists!";
        fi
      - echo "Done!"
  gen-init:
    desc: "Builds the init binary"
    cmds:
      - echo "Building init binary..."
      - go build --tags netgo --ldflags '-s -w -extldflags "-lm -lstdc++ -static"' -o init cmd/init/main.go
      - echo "Done!"
  
  gen-initrd:
    dir: ./cmd/initrd
    desc: "Builds the initrd"
    cmds:
      - echo "Generating initrd..."
      - go build -tags netgo
      - mkdir -p tmp
      - cp initrd tmp/init
      - cd tmp
      - find . -print0 | cpio --null --create --verbose --format=newc > ../../initrd.cpio
      - cd ..
      - rm -rf tmp
      - rm -rf initrd
      - echo "Done!"
  all:
    desc: "Builds the firecracker-land binary, pulls the kernel, builds the init binary, and generates the initrd"
    cmds:
      - task clean
      - go mod download
      - task pull-kernel
      - task gen-init
      - task gen-initrd
      - task build
      - task run
      - echo "Running firecracker-land binary..."